# Generated by Django 5.1.4 on 2025-01-06 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=10, null=True)),
                ("celular", models.CharField(max_length=10)),
                ("correo", models.EmailField(max_length=200, unique=True)),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Domicilio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pais", models.CharField(max_length=50)),
                ("estado", models.CharField(max_length=50)),
                ("municipio", models.CharField(max_length=50)),
                ("cp", models.IntegerField(max_length=5, verbose_name="Codigo postal")),
                ("colonia", models.CharField(max_length=50)),
                ("calle", models.CharField(max_length=50)),
                (
                    "ne",
                    models.IntegerField(max_length=50, verbose_name="Numero exterior"),
                ),
                (
                    "ni",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numero interior",
                    ),
                ),
                ("referencia", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfc", models.CharField(max_length=10, verbose_name="RFC")),
                ("rs", models.CharField(max_length=200, verbose_name="Razon social")),
                (
                    "domicilio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="venta.domicilio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Negocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "contacto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="venta.contacto",
                    ),
                ),
                (
                    "fiscal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="venta.fiscal",
                    ),
                ),
            ],
        ),
    ]
