# Generated by Django 5.1.4 on 2025-01-07 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0003_caja_departamento_marca_medida_cliente_producto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=11)),
                (
                    "total_descuento",
                    models.DecimalField(decimal_places=2, max_digits=11),
                ),
                ("importe", models.DecimalField(decimal_places=2, max_digits=11)),
                ("cambio", models.DecimalField(decimal_places=2, max_digits=11)),
                (
                    "caja",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="venta.caja",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="venta.cliente",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="venta.usuario",
                    ),
                ),
            ],
        ),
    ]
