# Generated by Django 5.1.4 on 2025-01-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0004_venta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="departamnto",
            new_name="departamento",
        ),
        migrations.AddField(
            model_name="usuario",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="users"),
        ),
    ]
