# Generated by Django 5.1.4 on 2025-01-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0006_alter_contacto_correo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacto",
            name="correo",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
