# Generated by Django 5.1.4 on 2025-01-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0007_alter_contacto_correo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="cambio",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="importe",
        ),
    ]
