# Generated by Django 5.1.4 on 2025-01-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0008_remove_venta_cambio_remove_venta_importe"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="cambio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="importe",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="mp",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Seleccione un metodo de pago"),
                    ("E", "Efectivo"),
                    ("T", "Transferencia"),
                    ("C", "Tarjeta de credito"),
                    ("D", "Tarjeta de debito"),
                ],
                max_length=1,
                null=True,
                verbose_name="Metodo de pago",
            ),
        ),
    ]
